dist: xenial
language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - cppcheck
script:
- perl -pi -e 's/^#ifdef SIGPOLL$/#if 1/' *.c  # "ifdef SIGPOLL" confuses cppcheck
- cppcheck --error-exitcode=1 *.c
- git checkout *.c
- make
- make test
- make -C doc
- make -C doc check
- make install PREFIX=~/.local
- cd /
- recidivm -h
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 recidivm | grep -A 10 -w RECIDIVM

# vim:ts=2 sts=2 sw=2 et
